### ISSUE TITLE
Bug: Invoking functions seems to be broken.

### ISSUE THREAD

**Issue by eahefnawy** [serverless/event-gateway-sdk#31] opened 2018-05-10 14:56 UTC
I get the following error when I try to invoke a function with the invoke method:

```
Failed to invoke function eg-test due the error: function or subscription not found
```

I've confirmed that both the function and the subscription exists by running the `listFunctions` and `listSubscriptions` methods.

**Comment by mthenw** [comment] 2018-05-14 09:35
Hey @eahefnawy,

can you provide more details of your subscription and invoke request. I cannot reproduce that.

**Comment by mthenw** [comment] 2018-05-15 07:48
@eahefnawy I'm closing this one. Let me know if you still have this issue.

**Closed by mthenw** 2018-05-15 07:48 UTC
